# Generated by Django 3.2.23 on 2024-11-30 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_discountcode_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='active',
            field=models.BooleanField(default=True, help_text='Toggle to enable/disable this discount code'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(help_text='Enter a unique discount code', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter discount percentage (0-100)', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
