# Generated by Django 3.2.23 on 2024-12-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20241129_1622'),
        ('checkout', '0003_auto_20241130_2224'),
    ]

    operations = [
    ]
