# Generated by Django 3.2.23 on 2024-11-29 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be at least 0.01'), django.core.validators.MaxValueValidator(999999.99, message='Price cannot exceed 999,999.99')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Rating cannot be negative'), django.core.validators.MaxValueValidator(5.0, message='Rating cannot exceed 5.0')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0, message='Rating must be at least 1.0'), django.core.validators.MaxValueValidator(5.0, message='Rating cannot exceed 5.0')]),
        ),
    ]
