# Generated by Django 3.2.23 on 2024-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/noimage.png', null=True, upload_to='product_images/'),
        ),
    ]
