# Generated by Django 3.2.23 on 2024-12-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='product_images/'),
        ),
    ]
